### ISSUE TITLE
Control chunking in response to client

### ISSUE THREAD

**Issue by luvolondon** [ledgetech/ledge#139]
Hallo,
thank you very much for your module. I'm using it to interpret simple ESI includes coming from a CMS and serve the final pages to browser clients. It works great. My problem is the chunks that are generated when the response stream is sent to the client. 
The idea is to be able to control the chunks with the use of ESI commands to allow progressive rendering of the html page: Have a first chunk with the above-the-fold HTML + critical CSS and a second chunk with the rest. This works great with a single ESI command inside the HEAD element. It doesnt work if I include a second ESI command inside the body.

This is the configuration I'm using:
(openresty/1.11.2.2)

```
worker_processes  1;
events {
    worker_connections  1024;
}

http {
	lua_check_client_abort On;
	init_by_lua_block {
		ledge = require("ledge.ledge").new()
		ledge:config_set("esi_enabled", true)
		ledge:config_set("upstream_host", "a.b.c.d")
		ledge:config_set("upstream_port", "8080")
		ledge:config_set("buffer_size", 2^18)
	}
	init_worker_by_lua_block {
		ledge:run_workers()
	}
	server {
		if_modified_since Off;
		listen       80;
		gzip            on;
		gzip_types      text/plain;

		location / {
			proxy_buffer_size 8k;
			proxy_set_header Host "website.com";
			proxy_set_header X-Forwarded-Host $host;
			proxy_set_header X-Forwarded-Server $host;
			add_header "Access-Control-Allow-Origin" "*";
			proxy_cookie_path /site/ /;
			rewrite_by_lua_block {
				local uri = ngx.re.sub(ngx.var.uri, "^/(.*)", "/site/$1", "o")
				ngx.req.set_uri(uri)
			}
			content_by_lua_block {
				local ck = require "resty.cookie"
                local cookie = ck:new()
				local function set_surrogate_response_header(res)
					local status = res.status
					if not res.header["Surrogate-Control"] and not (status > 300 and status < 303) then
						res.header["Surrogate-Control"] = 'content="ESI/1.0"'
					end
				end
				ledge:bind("origin_fetched", set_surrogate_response_header)
				local fullcss = cookie:get("fullcss")
					if not fullcss then
						local ok = cookie:set({
                    key = "fullcss", value = "true",expires = "ngx.cookie_time(ngx.time() + 2592000)", max_age = 2592000
					})
				end
				ledge:run()
			}
		}
	}
}
```

The HTML coming from the upstream server is built like this:

```
<HTML>
<HEAD>
	<esi:choose>
	<esi:when test="$(HTTP_COOKIE{fullcss}) == 'true'">
	<link rel="stylesheet" href="/css/app.css"/>" type="text/css"/>               
    </esi:when>
	<esi:otherwise>
	<esi:include src="/criticalcss" />
	</esi:otherwise>
	</esi:choose>
</HEAD>
<BODY>
... about 100k text...
</BODY>
</HTML>
```

The above page is delivered downstream in three chunks:

1 ... everything before ESI stuff...
2 ... ESI stuff
3 ... everything behind ESI stuff...

This is great. Unfortunatly if I add another ESI include inside the BODY of my HTML coming from the upstream server, the complete response gets split up into many chunks. Each chunk is only a few hundred bytes in size. Even the include from the 1st ESI include is split into several chunks. One chunk is even only 2 bytes long.

I've changed the different buffering configuration parameters in any possible way. 

Sadly I'm not yet very familiar with nginx/openresty. Is the chunking of the response stream controlled by your module or something done by the generic lua part of my installation?
Thank you very much for your advice!

Best regards
Lucas

**Comment by pintsized** [comment]
Hi Lucas,

In short, it's Nginx that controls the downstream chunking. We send data to the output buffers (with `ngx.print`) and let Nginx decide what's best in terms of chunking to the client.

When you use `esi:include`, it makes a request for that resource and streams it using the same buffer size that we use throughout, so mostly this should result in an `ngx.print` for each chunk received from upstream. Again, these just go to the Nginx output buffers. The one difference with `esi:include` however is that we call `ngx.flush` just before making the request, as a hint to Nginx to send what it has so far instead of waiting on this (potentially slow) upstream esi request.

With esi conditionals, we do call `ngx.print` quite often potentially. That is, each time it reaches a branch which evaluates to true, it'll yield that data right there and then. But again, this just goes to the output buffers and Nginx sends downstream whenever it decides. 

So I'm struggling to see how adding an include to your body changes the chunking behaviour for the entire page, beyond it somehow coercing Nginx into flushing buffers differently.

Are you able to try this with different content included, to see if you get the same behaviour / spot a pattern?

Also, are you sure it's actually a problem? Generally we just trust Nginx to do the right thing. Does the chunking affect performance in some way?

James.

**Comment by luvolondon** [comment]
James,
thank you very much, this is exactly the information I need. Setting up different content to spot a pattern will be my next step now.

I'm sure you're right about the limited impact of chunks on performance. 
My primary interest is to find a relation between esi:includes, the chunks delivered to the client and the progressive rendering done by the browser. I'ld like to control the progressive rendering steps by defining esi sections within the templates of a website. 

From your explanation I understand I need to look at nginx´s buffering behavior. I guess the chunking has to do with ngx.flush being called. Does this also happen if no upstream connection is needed to complete the esi:include?
Example:
`<esi:include src="/data" />
`
```
location /data {
  content_by_lua_block {
  local ck = require "resty.cookie"
  local cookie = ck:new()
  local fullcss = cookie:get("fullcss")
  if fullcss then  
    ngx.say "Cookie"
  else
    ngx.say "No Cookie"
  end
}
```

And are there other esi commands that trigger a ngx.flush apart from esi:include?

Again, thank very much for your time and efforts to help. From here on I'll move my focus to the nginx core. 
Best regards,
Lucas

**Comment by pintsized** [comment]
> I guess the chunking has to do with ngx.flush being called. Does this also happen if no upstream connection is needed to complete the esi:include?

Yes. Well, there's always an upstream connection, just it happens to be a loopback in your case, but the ESI processor doesn't know that. Note that we call `ngx.flush()` which is asynchronous (i.e. doesn't wait until flushed). We find that generally it results in the first bytes being sent to the client whilst the ESI include is fetched, but we don't force this to happen synchronously with `ngx.flush(true)`. So if your include doesn't involve outbound network i/o and is fast to respond, then you may see your include buffered before Nginx next decides to flush. Again this generally makes sense to us; just trust the Nginx output buffer chain to do the right thing.

> And are there other esi commands that trigger a ngx.flush apart from esi:include?

No, the only time we flush is when we know we've got to do network i/o with an include. It's really just a hint "please don't wait with buffers because this might take a while". But like I said, it's not synchronous so the flush isn't guaranteed to beat the include. (You could change this line to `ngx.flush(true)` and see what happens, but it's probably not a great idea in most cases).

I would say that in general, using esi includes should do what you're asking for. Anything before each include will be flushed whilst the include is happening. That is, in principle I think you'll see the desired behaviour, but you might not be able to reliably test for it, especially if the include doesn't introduce latency as it may be buffered by Nginx.

HTH.

**Comment by luvolondon** [comment]
I understand, and it corresponds to the results of my testing:
If the result of an esi:include is generated fast, it has no influence on the "chunking". Even when I change the flush call to flush(true) in your code. As you say: Nginx decides on it's own when it is time to start a new chunk.
A next step will be to look at the nginx core how I could sync the esi:include to the chunking. 
Atm I configure nginx with these buffer, this way I'm at least getting several chunks and the client browser is able to start with progressive rendering. Though I still have to find out, if the increased number of chunks lead to unwanted reflow events in the browser.
proxy_buffering on;
proxy_buffer_size 600;
proxy_buffers 10 600;
proxy_busy_buffers_size 600;
chunked_transfer_encoding on;

Thank you very much for your time and expertise.
Best regards,
Lucas

**Comment by pintsized** [comment]
Those `proxy_*` settings are specifically for the Nginx proxy module, and so will only have a bearing on content which you're fetching using that module, (which perhaps you aren't?). Ledge fetches upstream using Lua cosockets rather than the proxy module.

I'm surprised `ngx.flush(true)` has no impact. Just to clarify, it won't directly change how Nginx decides to do transfer encoding, but it will make Nginx send what it has in the buffers so far immediately. When you say "chunks" do you mean transfer encoded chunks, or do you mean bytes as they appear on the wire?

Are you testing with HTTP 1.0 by any chance? You'll see different behaviours there, and `ngx.flush(true)` wont work as expected if HTTP 1.0 buffering is on (which is the default): https://github.com/openresty/lua-nginx-module#lua_http10_buffering

Again, whilst I may be missing something in your requirements, the only time you should see content before an `esi:include` not sent until after the include, is if the include was so fast it was able to produce the content before Nginx had a chance to flush its buffers. In other words, when you have a latency problem, the content will be flushed up to that point, and when you don't, ...well you don't have a problem ;)

**Comment by luvolondon** [comment]
James, you're absolutely right. I did more testing and the count of transfer encoded chunks don't correlate with the "proxy_*" settings. The output varies between 3-10 chunks. It all just depends on the time it takes the upstream server to deliver the esi:include data for the HEAD include (about 16k).  

I'm retrieving the response with "curl -iv --raw". Transfer encoded chunks can be seen with their starting byte count, though they are gunzipped already. I also use Fiddler to view the chunks. curl does HTTP 1.1, if I run curl with "--http1.0" I don't get transfer encoded chunks at all.

I'll write down the flush(true) test in the next post.

**Comment by luvolondon** [comment]
"flush(true)" test:
Response from upstream server:
```
<HTML>
<HEAD>
	<esi:include src="/data1" />
</HEAD>
<BODY>
... about 20k HTML  ...
	<esi:include src="/data2" />
... about 80k HTML ...
</BODY>
</HTML>
```
Both esi:includes got requested from the upstream server and delivered about 16k of html code. I executed _flushall_ in redis-cli before every test.
To test the influence of the "true" parameter when using "ngx.flush" I changed "flush()" in esi.lua to
```
ngx.say("!1!")
ngx_flush(true)
```
The resulting output had the !1! marker and the html from /data1 and /data2. While the data1 part is _always_ placed into a new transfer encoded chunk the /data2 part is never. Depending on some other factor (speed/delay of the upstream server?) the output is separated into many chunks. But this is rather happening within the /data1 part and below. There is no chunk started before /data2 (or close to it).

**Comment by pintsized** [comment]
Hi, is this still an outstanding issue for you? The serving code has changed with regards to flush behaviour in the new version (now on the master branch). Let me know if you need further help.

(Be warned, the new version (in master) is a complete refactor with all new config systems and updated docs.)
