### ISSUE TITLE
HTTP v2 not supported yet

### ISSUE THREAD

**Issue by patrickporto** [ledgetech/ledge#179]
Hi,
I am trying to execute the command `handle:run()` but the output is being `http v2 not supported yet`:

```
kong-proxy_1      | 2018/09/17 13:55:12 [error] 38#0: *52 [lua] handler.lua:456: fetch_from_origin(): error getting client body reader: http v2 not supported yet, client: 172.21.0.1, server: kong, request: "GET / HTTP/2.0", host: "debug-upstream"
```

My code:

```lua
local handler = ledge.create_handler({
    upstream_host = 'debug-upstream',
    upstream_port = 8000,
    storage_driver_config = {
        redis_connector_params = {
            url = "redis://mycache:6379/0",
        }
    }
})
local _, err = handler:run()
if err then
    ngx.log(ngx.ERR, err)
end
```

**Comment by hamishforbes** [comment]
This is because `ngx.req.socket` in the nginx Lua module does [not support](https://github.com/openresty/lua-nginx-module#spdy-mode-not-fully-supported) HTTP2/SPDY.

So we can't read the request body in a streaming fashion within Lua for an HTTP/2 request.

I'd recommend you use a nginx's native proxy_pass functionality to do http2 -> http1.1 and run Ledge in the 1.1 server.
