### ISSUE TITLE
How to decouple range (range.lua) module?

### ISSUE THREAD

**Issue by mauricioabreu** [ledgetech/ledge#195]
First, I am sorry for opening an issue to make a question. I know it is not good but this question is too specific for Stack Overflow. Please, close this issue if you think it is inappropriate.

---

I am facing a problem trying to deliver MP4 videos using Lua + NGINX. There is a problem when making a subrequest using Lua and byte-range: Lua's subrequest is simple and does not have this feature, it ignores the `Range` header.

I found your project and it is awesome, but I can't use it right now. `range.lua` is well written and it could help me to deliver big files using the `Range` header.

Trying to decouple the code, I got stuck copying/using the `get_range_request_filter` function. What is the [reader](https://github.com/mauricioabreu/nginx_bytes_range/blob/byte-range-support/lib/range.lua#L298)? Where should I set the [buffer_size](https://github.com/mauricioabreu/nginx_bytes_range/blob/byte-range-support/lib/range.lua#L304)?

Here is my [nginx conf](https://github.com/mauricioabreu/nginx_bytes_range/blob/byte-range-support/nginx.conf#L50)

```
local res, partial_response = range:handle_range_request(dres)
local body_reader = coroutine.wrap(function()
    coroutine.yield("01234")
    coroutine.yield("56789")
end)
if partial_response then
    res.body_reader = range:get_range_request_filter(
        body_reader
    )
end

local body = read_body(res)
ngx.status = res.status
ngx.say(body)
```

Request example:
```
curl -v -r 0-10 http://127.0.0.1:8080/r > /dev/null
```

What I got? full response

What I expected: a piece of the body, using the `Range` header value.

Can you help me?

**Comment by pintsized** [comment]
I think what you're trying to do should be possible, but I'll confess it's been a while since I looked at this. It is proven code however, so if you get it hooked up correctly you should definitely be able to rely on it.

The `body_reader` (as you seem to have already worked out) is a generic function used throughout Ledge, since we stream the body optionally through one or more filters (range, but also for ESI and so on). The function needs to return (or yield) body chunks until finished, and generally that's implemented as a coroutine which wraps and reads from the previous top-most reader in the chain - so once installed they all pull from each other, the inner-most reader being either the upstream socket stream, or the redis stream - it all looks the same.

Ledge has this state machine concept which will "install_x_filter" and so on, just to help make sense of all the myriad possibilities with generic traffic and ensures the filters are installed in a sane order, but you don't really need that. You just need to create the filter, which you seem to be doing correctly as far as I can see.

Things are a little different for you since your `res` is from a location block capture, whereas in Ledge it is always [one of these](https://github.com/ledgetech/ledge/blob/master/lib/ledge/response.lua). I remember making the interface match the location capture where possible, but important to keep in mind that in Ledge it isn't used in that way.

So in your case, rather than streaming you'll be loading the entire resource into memory with the location capture. You'll then want to create a body reader which reads from that data. Essentially a little proxy reader function onto the `res.body` field. Again, by convention we pass in a buffer size so that things are streamed in predictable chunks, but in your case you're buffering the whole thing anyway so this isn't really important.

You can at least avoid re-concatenating everything as you are in your `read_body` function. Better to just `ngx.print` the filtered chunks as they appear rather than build a new body string.

If it isn't working, you'll want to investigate whether the range processor is deciding not to filter anything for some reason (inspect the headers and so on)

Hope some of that is useful.

**Comment by mauricioabreu** [comment]
@pintsized so much thank you! Your answer helped me a lot. Have a nice day!
